### ISSUE TITLE
"unexpected frame by generating stack"

### ISSUE THREAD

**Issue by wmertens** [inf3rno/error-polyfill#32]
Somehow, running react in codesandbox in firefox generates this error, I think it's caused by trying to get a stack by calling `captureStackTrace`.

Firefox 65

Triggered by https://codesandbox.io/s/j70v45wz85 - works in Chrome

**Comment by inf3rno** [comment]
@wmertens Thanks for reporting, I'll try to investigate it this week.

**Comment by inf3rno** [comment]
@wmertens Can I ask a few question about how you use the library?

**Comment by wmertens** [comment]
@inf3rno sure but it's actually used by codesandbox, I didn't add it. I think the slate library is calling it to get a code location.

**Comment by wmertens** [comment]
so just loading the project in firefox causes the error, in Chrome it's fine

**Comment by inf3rno** [comment]
@wmertens I checked meanwhile, the tests of the published version succeed, so the library might interfere with React. I am not sure how, I'd need to debug this, which can take a lot of time. I might give it a try at weekend.

I'd rather write a separate repo instead of a polyfill, because it is not possible to override Error.prototype.stack in some of the environments and conflicts with existing libraries, like the current one can happen. What do you think about this? Do you think it is important to have the same V8 Error API, or would you use something slightly different e.g. `stack = lib.captureStackTrace(func)` instead of `Error.captureStackTrace(obj, func)`?

Afaik. Bower is a dead package manager. I'd rather remove it completely from my repos and keep npm only. Do you think I should keep bower support?

**Comment by wmertens** [comment]
Did some more digging - https://github.com/CompuIves/codesandbox-client/blob/096366fdf8543474c2ccea049920749b748d46f5/packages/common/load-dynamic-polyfills.js loads the polyfill in the codesandbox environment.

My sandbox loads slate, which tries to run Error.captureStackTrace. That then crashes in Firefox for some reason. https://github.com/ianstormtaylor/slate/blob/ded82812b0949769e8c64130f7117cf75ee76ed7/packages/slate/src/utils/slate-error.js#L16

So to reproduce, you just need to breakpoint the error location in that sandbox, just visit https://j70v45wz85.codesandbox.io/ with FireFox

**Comment by wmertens** [comment]
As for your other questions, I think codesandbox uses your lib to provide that v8 API in other browsers, so if it's not a polyfill I think they won't use it…

And indeed, I didn't use Bower since 2013 and I don't know anyone who still uses it :) I wouldn't support it either.

**Comment by inf3rno** [comment]
@wmertens I see, so they just need the captureStackTrace from the polyfill.

**Comment by inf3rno** [comment]
@wmertens I think I know what the problem is. They give `this.constructor` as param and the polyfill does not find which frame belongs to it, hence it does not know where to truncate the stack string, which it gets from catching `throw new Error`. I might add a console warning and don't truncate in these cases instead of throwing an error. That would be an ugly fix.
This is an old an unsolvable problem. It is not always possible to find which frame belongs to such parameters, because all you can work with is the function name and the stack trace and if the function does not have a name or 2 functions have the same names in the stack trace, then you have a problem...
There is no workaround for this, partially that's why I did not want to continue this lib and develop the e3 project instead where you can extend e3.UserError and where you can even count how many frames to remove from the stack...
I wonder why ppl use this polyfill, it has a 0.1.x version and it is "unstable" if you check the repo description. I might deprecate it, I am not sure. I'll talk to these guys and decide it later.

**Comment by inf3rno** [comment]
I checked this and the bug is even more interesting.
The code works with normal constructors:
```js
            var A = function (){
                Error.captureStackTrace(aThrowable, this.constructor);
            };
            new A();
```
While it throws the error when we use ES6 classes.
```js
            class A {
                constructor(){
                    Error.captureStackTrace(aThrowable, this.constructor);
                }
            }
            new A();
```

Idk. what is the problem, I'll investigate this further.

**Comment by inf3rno** [comment]
I have found the cause. The code uses `arguments.callee.caller` to extract the list of the called functions. I solved the upper problem this way if this deprecated feature is available. Whenever the callee or the caller is an ES6 class constructor, it throws an error instead of returning that constructor. This appears to be a Firefox bug. I'll report it to Firefox devs, and I'll try to write a workaround.

**Comment by inf3rno** [comment]
@wmertens I sent a bug report to Firefox devs about this: https://bugzilla.mozilla.org/show_bug.cgi?id=1527810 They don't want to fix it. I wrote a patch for Firefox, so this won't affect the lib any longer. Thanks for the report!

**Comment by inf3rno** [comment]
I checked the code sandbox client: https://github.com/CompuIves/codesandbox-client/blob/096366fdf8543474c2ccea049920749b748d46f5/packages/common/package.json
They use "^0.1.1", so as far as I understand NPM will automatically download the 0.1.2 version because of the "^" when somebody installs their lib.

**Comment by wmertens** [comment]
Wonderful! Thank you for your library and your work!
